# Neovim for the dev shell, set up for Rust out of the box.
#
# Plugins come from nixpkgs and the config is baked in, so nothing is
# downloaded at runtime (no lazy.nvim, no Mason). rust-analyzer is not
# bundled here: it comes from the flake's toolchain, so it always matches
# the rustc you build with.
{ pkgs }:

let
  plugins = with pkgs.vimPlugins; [
    # LSP defaults for rust_analyzer; enabled with vim.lsp.enable below
    nvim-lspconfig
    blink-cmp
    (nvim-treesitter.withPlugins (p: with p; [
      rust
      toml
      nix
      lua
      yaml
      json
      markdown
      markdown_inline
    ]))
    # versions and features for Cargo.toml dependencies
    crates-nvim
    telescope-nvim
    telescope-fzf-native-nvim
    plenary-nvim
    gitsigns-nvim
    which-key-nvim
    tokyonight-nvim
  ];

  initLua = ''
    -- Generated by nix/neovim.nix — edit that file, not this one.

    vim.g.mapleader = " "
    vim.g.maplocalleader = " "

    local o = vim.opt
    o.number = true
    o.relativenumber = true
    o.signcolumn = "yes"
    o.termguicolors = true
    o.mouse = "a"
    o.clipboard = "unnamedplus"
    o.ignorecase = true
    o.smartcase = true
    o.undofile = true
    o.splitright = true
    o.splitbelow = true
    o.scrolloff = 8
    o.updatetime = 250
    o.expandtab = true
    o.shiftwidth = 4
    o.tabstop = 4

    vim.cmd.colorscheme("tokyonight-night")

    -- Tree-sitter: parsers are prebuilt by Nix; just switch highlighting on.
    vim.api.nvim_create_autocmd("FileType", {
      callback = function(args)
        pcall(vim.treesitter.start, args.buf)
      end,
    })

    -- Completion
    local blink = require("blink.cmp")
    blink.setup({
      keymap = { preset = "default" }, -- <C-y> accept, <C-n>/<C-p> move
      signature = { enabled = true },
      fuzzy = { implementation = "prefer_rust" },
    })

    -- LSP
    vim.lsp.config("*", { capabilities = blink.get_lsp_capabilities() })
    vim.lsp.config("rust_analyzer", {
      settings = {
        ["rust-analyzer"] = {
          check = { command = "clippy" },
          cargo = { allFeatures = true },
          procMacro = { enable = true },
        },
      },
    })
    vim.lsp.enable({ "rust_analyzer", "nil_ls" })

    vim.diagnostic.config({ virtual_text = true, severity_sort = true })

    vim.api.nvim_create_autocmd("LspAttach", {
      callback = function(args)
        local map = function(keys, fn, desc)
          vim.keymap.set("n", keys, fn, { buffer = args.buf, desc = desc })
        end
        -- Neovim's defaults already cover K, grn (rename), gra (code action),
        -- grr (references) and gri (implementation).
        map("gd", vim.lsp.buf.definition, "Go to definition")
        map("<leader>f", function() vim.lsp.buf.format({ async = true }) end, "Format")
        map("<leader>ih", function()
          vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
        end, "Toggle inlay hints")

        -- rustfmt on save
        vim.api.nvim_create_autocmd("BufWritePre", {
          buffer = args.buf,
          callback = function() vim.lsp.buf.format({ bufnr = args.buf }) end,
        })
      end,
    })

    require("crates").setup({ lsp = { enabled = true, actions = true, completion = true, hover = true } })
    require("gitsigns").setup()
    require("which-key").setup()

    -- Telescope
    local telescope = require("telescope")
    telescope.setup({
      defaults = { file_ignore_patterns = { "^target/", "^%.git/", "^%.direnv/" } },
    })
    pcall(telescope.load_extension, "fzf")
    local tb = require("telescope.builtin")
    vim.keymap.set("n", "<leader>ff", tb.find_files, { desc = "Find files" })
    vim.keymap.set("n", "<leader>fg", tb.live_grep, { desc = "Grep" })
    vim.keymap.set("n", "<leader>fb", tb.buffers, { desc = "Buffers" })
    vim.keymap.set("n", "<leader>fs", tb.lsp_document_symbols, { desc = "Symbols" })
    vim.keymap.set("n", "<leader>fd", tb.diagnostics, { desc = "Diagnostics" })
  '';
in
pkgs.neovim.override {
  configure = {
    customLuaRC = initLua;
    packages.daedalus.start = plugins;
  };
}
