# The interactive shell for `nix develop`: zsh + oh-my-zsh (agnoster) + fzf.
#
# Everything lives in the Nix store, which is read-only, so anything that wants
# to write (history, completion dumps, oh-my-zsh's cache) is pointed at
# $DAEDALUS_STATE — see the `stateDir` argument.
{ pkgs }:

let
  inherit (pkgs) lib;

  # Sourced directly rather than via oh-my-zsh's plugin mechanism: the bundled
  # plugins shell out to locate these, which does not work against the store.
  fzfShare = "${pkgs.fzf}/share/fzf";
  omz = "${pkgs.oh-my-zsh}/share/oh-my-zsh";

  zshrc = pkgs.writeText "daedalus-zshrc" ''
    # Generated by flake.nix — do not edit. Put personal overrides in
    # ~/.zshrc.daedalus.local, which is sourced at the very end.

    # ---------------------------------------------------------------- state --
    # $DAEDALUS_STATE is exported by the devShell's shellHook.
    : "''${DAEDALUS_STATE:=$PWD/.direnv/daedalus}"
    mkdir -p "$DAEDALUS_STATE/ohmyzsh/completions"

    # -------------------------------------------------------------- history --
    export HISTFILE="$DAEDALUS_STATE/zsh_history"
    HISTSIZE=100000
    SAVEHIST=100000
    setopt EXTENDED_HISTORY INC_APPEND_HISTORY SHARE_HISTORY
    setopt HIST_IGNORE_ALL_DUPS HIST_IGNORE_SPACE HIST_REDUCE_BLANKS
    setopt HIST_VERIFY

    # ------------------------------------------------------------ oh-my-zsh --
    export ZSH="${omz}"
    # oh-my-zsh writes caches and its compdump; both must be outside the store.
    export ZSH_CACHE_DIR="$DAEDALUS_STATE/ohmyzsh"
    export ZSH_COMPDUMP="$ZSH_CACHE_DIR/zcompdump-''${ZSH_VERSION}"

    ZSH_THEME="agnoster"

    # The store copy can never update itself; skip the checks entirely.
    zstyle ':omz:update' mode disabled
    DISABLE_AUTO_UPDATE=true
    DISABLE_UPDATE_PROMPT=true
    COMPLETION_WAITING_DOTS=true

    # fzf, autosuggestions and syntax-highlighting are sourced by hand below
    # so they resolve to store paths instead of being searched for.
    plugins=(
      git
      rust
      kubectl
      helm
      docker-compose
      dirhistory
      colored-man-pages
    )

    source "$ZSH/oh-my-zsh.sh"

    # ----------------------------------------------------------- agnoster ----
    # agnoster's leftmost segment is user@host, which is noise in a project
    # shell. Replace it with a marker that says which devShell you are in.
    prompt_context() {
      prompt_segment black default "%{%F{cyan}%}❄%{%F{default}%} daedalus"
    }

    # agnoster needs a Powerline-patched font for  and . If you see boxes
    # or question marks, install one and select it in your terminal:
    #   https://github.com/ryanoasis/nerd-fonts  (MesloLGS NF is a good default)

    # ---------------------------------------------------------------- fzf ----
    # Ctrl-R history, Ctrl-T files, Alt-C directories.
    source "${fzfShare}/key-bindings.zsh"
    source "${fzfShare}/completion.zsh"

    # fd honours .gitignore; also skip Rust build output and the nix state dir.
    _dae_fd_excludes=(--exclude .git --exclude target --exclude .direnv)
    export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow ''${_dae_fd_excludes[*]}"
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND="fd --type d --hidden --follow ''${_dae_fd_excludes[*]}"

    export FZF_DEFAULT_OPTS="
      --height 45% --layout=reverse --border=rounded --info=inline
      --prompt='➜ ' --pointer='▶' --marker='✓'
      --bind 'ctrl-/:toggle-preview,ctrl-a:select-all'
    "
    export FZF_CTRL_T_OPTS="
      --preview 'bat --style=numbers --color=always --line-range=:300 {} 2>/dev/null
                 || eza --tree --level=2 --color=always {} 2>/dev/null'
      --preview-window=right:60%:wrap
    "
    export FZF_ALT_C_OPTS="--preview 'eza --tree --level=2 --color=always {}'"
    export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window=down:3:wrap --bind '?:toggle-preview'"

    # fzf-tab replaces the completion menu with fzf. Must load after compinit,
    # which oh-my-zsh has already run, and before syntax-highlighting.
    source "${pkgs.zsh-fzf-tab}/share/fzf-tab/fzf-tab.plugin.zsh"
    zstyle ':fzf-tab:*' fzf-flags --height=45% --layout=reverse --border=rounded
    zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza --tree --level=2 --color=always $realpath'
    zstyle ':completion:*' menu no

    # ------------------------------------------------------------- plugins ---
    source "${pkgs.zsh-autosuggestions}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"

    # Syntax highlighting must come after everything that defines widgets.
    source "${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

    # ...and history-substring-search after highlighting, or its widgets get
    # wrapped incorrectly. Up/Down search on what you have already typed.
    source "${pkgs.zsh-history-substring-search}/share/zsh-history-substring-search/zsh-history-substring-search.zsh"
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down
    bindkey -M vicmd 'k' history-substring-search-up
    bindkey -M vicmd 'j' history-substring-search-down

    # ---------------------------------------------------------------- misc ---
    eval "$(zoxide init zsh)"
    eval "$(direnv hook zsh)" 2>/dev/null || true

    # Deliberately not shadowing `grep` or `cat`: ripgrep's flags differ from
    # grep's (-E means --encoding, not --extended-regexp) and silently changing
    # that under muscle memory causes more confusion than it saves typing.
    alias ls='eza --group-directories-first'
    alias ll='eza -l --git --group-directories-first'
    alias la='eza -la --git --group-directories-first'
    alias lt='eza --tree --level=2'
    alias g='git'
    alias lg='lazygit'
    alias k='kubectl'
    alias vim='nvim'
    alias vi='nvim'

    # Project shorthands, mirroring the justfile in docs/plan/phase-0.
    alias c='cargo'
    alias cb='cargo build'
    alias ct='cargo nextest run --workspace'
    alias cc='cargo clippy --workspace --all-targets --all-features -- -D warnings'
    alias cf='cargo fmt --all'
    alias cw='bacon'

    # Fuzzy-jump to any file in the repo and open it in $EDITOR.
    fe() {
      local f
      f=$(fzf --query="$1" --select-1 --exit-0) && [ -n "$f" ] && ''${EDITOR:-vi} "$f"
    }

    # Fuzzy-checkout a git branch.
    fb() {
      local b
      b=$(git branch --all --color=always --sort=-committerdate \
          | grep -v HEAD | fzf --ansi --preview 'git log -20 --oneline --color=always {+1}') \
        && git checkout "$(echo "$b" | sed 's#^[* ]*##; s#^remotes/[^/]*/##')"
    }

    [ -f "$HOME/.zshrc.daedalus.local" ] && source "$HOME/.zshrc.daedalus.local"
  '';

in
# ZDOTDIR must be a directory containing .zshrc, so wrap the file in one.
pkgs.runCommand "daedalus-zdotdir" { } ''
  mkdir -p $out
  ln -s ${zshrc} $out/.zshrc
''
